# Locations of the Next.js storefront (dmp.client) server.

location / {
    include /etc/nginx/include/nextjs-defaults.conf;

    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Robots-Tag $robots_tag;

    location = /robots.txt {
        access_log off;
        log_not_found off;
        include /etc/nginx/include/nextjs-defaults.conf;
        include /etc/nginx/include/no-cache.conf;
    }
}

location ~* ^/_next {
    include /etc/nginx/include/nextjs-defaults.conf;

    location ~* ^/_next/data {
        include /etc/nginx/include/nextjs-defaults.conf;
        include /etc/nginx/include/no-cache.conf;
    }
}

location ~ ^/api/ {
    include /etc/nginx/include/api-proxy.conf;
}

location ~ ^/(sitemap).*\.xml$ {
    include /etc/nginx/include/nextjs-defaults.conf;
    include /etc/nginx/include/no-cache.conf;
}
